{"name": "test_success_create_task", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('get_list_id', <FixtureRequest for <Function test_success_create_task>>)", "trace": "file c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\api\\test_tasks.py, line 15\n      @allure.description(\"Проверка успешного создания задачи\")\n      def test_success_create_task(self, tasks_client, get_list_id):\nE       fixture 'get_list_id' not found\n>       available fixtures: _verify_url, auth_session, authorized_user, base_url, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, clickup_ids, create_and_delete_task, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, sync_browser, tasks_client, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nc:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\api\\test_tasks.py:15"}, "description": "Проверка успешного создания задачи", "start": 1744799742470, "stop": 1744799742470, "uuid": "7fbe0b02-1351-451e-a615-65f60c4d6e64", "historyId": "4fefddb7f118c63b054dd34a1f7caadb", "testCaseId": "4fefddb7f118c63b054dd34a1f7caadb", "fullName": "tests.api.test_tasks.TestTasks#test_success_create_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "25968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}