{"name": "test_fail_delete_task", "status": "passed", "description": "Проверка ошибки при удалении задачи с некорректными заголовками", "steps": [{"name": "Обновляем заголовки на некорректные", "status": "passed", "start": 1744799923644, "stop": 1744799923644}, {"name": "Пытаемся удалить задачу", "status": "passed", "start": 1744799923644, "stop": 1744799923858}, {"name": "Возвращаем заголовки и убеждаемся, что задача осталась", "status": "passed", "start": 1744799923858, "stop": 1744799924233}], "start": 1744799923644, "stop": 1744799924233, "uuid": "d70734bb-41da-478c-aa02-228d983afed4", "historyId": "fca0feda91469001c721842c2aa8b58f", "testCaseId": "fca0feda91469001c721842c2aa8b58f", "fullName": "tests.api.test_tasks.TestTasks#test_fail_delete_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "33020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}