{"uuid": "286b5d3a-b2ed-4e8d-b009-5548806bba22", "children": ["9a6ea842-05f9-4a69-99a8-02f049d845fb", "84d74235-af95-47e4-ad1a-2e3b10dfa70a"], "befores": [{"name": "sync_browser", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nPlease use the Async API instead.\n", "trace": "  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py\", line 100, in sync_browser\n    playwright = sync_playwright().start()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_context_manager.py\", line 84, in start\n    return self.__enter__()\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_context_manager.py\", line 47, in __enter__\n    raise Error(\n"}, "steps": [{"name": "Запуск браузера Playwright", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nPlease use the Async API instead.\n", "trace": "  File \"c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py\", line 100, in sync_browser\n    playwright = sync_playwright().start()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_context_manager.py\", line 84, in start\n    return self.__enter__()\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_context_manager.py\", line 47, in __enter__\n    raise Error(\n"}, "start": 1744800160382, "stop": 1744800160382}], "start": 1744800160382, "stop": 1744800160382}], "start": 1744800160382, "stop": 1744800160396}