{"name": "test_fail_delete_task", "status": "passed", "description": "Проверка ошибки при удалении задачи с некорректными заголовками", "steps": [{"name": "Обновляем заголовки на некорректные", "status": "passed", "start": 1744800213808, "stop": 1744800213808}, {"name": "Пытаемся удалить задачу", "status": "passed", "start": 1744800213808, "stop": 1744800214041}, {"name": "Возвращаем заголовки и убеждаемся, что задача осталась", "status": "passed", "start": 1744800214041, "stop": 1744800214394}], "start": 1744800213808, "stop": 1744800214394, "uuid": "25cbc580-e109-4f55-a628-b988c76c768b", "historyId": "fca0feda91469001c721842c2aa8b58f", "testCaseId": "fca0feda91469001c721842c2aa8b58f", "fullName": "tests.api.test_tasks.TestTasks#test_fail_delete_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "16732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}