{"name": "test_success_update_task", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('get_list_id', <SubRequest 'create_and_delete_task' for <Function test_success_update_task>>)", "trace": "file c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\api\\test_tasks.py, line 65\n      @allure.description(\"Проверка успешного обновления задачи\")\n      def test_success_update_task(self, tasks_client, create_and_delete_task):\nfile c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py, line 28\n  @pytest.fixture\n  def create_and_delete_task(get_list_id):\nE       fixture 'get_list_id' not found\n>       available fixtures: _verify_url, auth_session, authorized_user, base_url, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, clickup_ids, create_and_delete_task, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, sync_browser, tasks_client, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nc:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py:28"}, "description": "Проверка успешного обновления задачи", "start": 1744799742480, "stop": 1744799742480, "uuid": "59829a00-2bb2-41b2-b304-222ac5292ef6", "historyId": "4acaf84e486872c49d6a88471c0c16c2", "testCaseId": "4acaf84e486872c49d6a88471c0c16c2", "fullName": "tests.api.test_tasks.TestTasks#test_success_update_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "25968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}