{"name": "test_fail_delete_task", "status": "passed", "description": "Проверка ошибки при удалении задачи с некорректными заголовками", "steps": [{"name": "Обновляем заголовки на некорректные", "status": "passed", "start": 1744798875800, "stop": 1744798875800}, {"name": "Пытаемся удалить задачу", "status": "passed", "start": 1744798875800, "stop": 1744798876020}, {"name": "Возвращаем заголовки и убеждаемся, что задача осталась", "status": "passed", "start": 1744798876020, "stop": 1744798876397}], "start": 1744798875799, "stop": 1744798876397, "uuid": "a3dc4c64-97bf-44d3-b940-75626d5ebc3b", "historyId": "fca0feda91469001c721842c2aa8b58f", "testCaseId": "fca0feda91469001c721842c2aa8b58f", "fullName": "tests.api.test_tasks.TestTasks#test_fail_delete_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "2352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}