{"name": "test_success_login", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"", "trace": "self = <clickup_tests.tests.ui.test_login_page.TestLogin object at 0x0000023871659310>\nsync_browser = <Browser type=<BrowserType name=chromium executable_path=C:\\Users\\Sanchez\\AppData\\Local\\ms-playwright\\chromium-1161\\chrome-win\\chrome.exe> version=134.0.6998.35>\n\n    @allure.description(\"Проверка успешного входа в систему\")\n    def test_success_login(self, sync_browser):\n        with allure.step(\"Создаём новую страницу браузера\"):\n            page = sync_browser.new_page()\n    \n        with allure.step(\"Выполняем логин с корректными данными\"):\n            login_page = LoginPage(page)\n>           login_page.login(CLICKUP_EMAIL, CLICKUP_PASSWORD)\n\ntests\\ui\\test_login_page.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\login_page.py:14: in login\n    self.navigate_to()\npages\\base_page.py:18: in navigate_to\n    self.page.goto(full_url)\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9020: in goto\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py:552: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Connection object at 0x00000238716254C0>, cb = <function Channel.send.<locals>.<lambda> at 0x00000238718D2CA0>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nE           Call log:\nE             - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TargetClosedError"}, "description": "Проверка успешного входа в систему", "steps": [{"name": "Создаём новую страницу браузера", "status": "passed", "start": 1744825760828, "stop": 1744825760934}, {"name": "Выполняем логин с корректными данными", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Page.goto: Target page, context or browser has been closed\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\ui\\test_login_page.py\", line 16, in test_success_login\n    login_page.login(CLICKUP_EMAIL, CLICKUP_PASSWORD)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\pages\\login_page.py\", line 14, in login\n    self.navigate_to()\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\pages\\base_page.py\", line 18, in navigate_to\n    self.page.goto(full_url)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1744825760934, "stop": 1744825764543}], "start": 1744825760828, "stop": 1744825764543, "uuid": "00075283-04af-4255-ad83-4a486eece026", "historyId": "07d8874e73237e03be0dfcb2178cf1be", "testCaseId": "07d8874e73237e03be0dfcb2178cf1be", "fullName": "tests.ui.test_login_page.TestLogin#test_success_login", "labels": [{"name": "feature", "value": "UI: Авторизация"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_login_page"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "31176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_login_page"}]}