{"name": "test_fail_login", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nPlease use the Async API instead.", "trace": "@pytest.fixture(scope=\"session\")\n    def sync_browser():\n        with allure.step(\"Запуск браузера Playwright\"):\n>           playwright = sync_playwright().start()\n\ntests\\conftest.py:84: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n.venv\\Lib\\site-packages\\playwright\\sync_api\\_context_manager.py:84: in start\n    return self.__enter__()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright.sync_api._context_manager.PlaywrightContextManager object at 0x000001C95F669010>\n\n        def __enter__(self) -> SyncPlaywright:\n            try:\n                self._loop = asyncio.get_running_loop()\n            except RuntimeError:\n                self._loop = asyncio.new_event_loop()\n                self._own_loop = True\n            if self._loop.is_running():\n>               raise Error(\n                    \"\"\"It looks like you are using Playwright Sync API inside the asyncio loop.\n    Please use the Async API instead.\"\"\"\n                )\nE               playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nE               Please use the Async API instead.\n\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_context_manager.py:47: Error"}, "description": "Проверка ошибки при некорректном пароле", "start": 1744799760458, "stop": 1744799760458, "uuid": "3f6ad8a2-2ce9-4824-acc6-1c1c05ebb4ec", "historyId": "4f543d8847a5db1fd4946b1c5ad7c73b", "testCaseId": "4f543d8847a5db1fd4946b1c5ad7c73b", "fullName": "tests.ui.test_login_page.TestLogin#test_fail_login", "labels": [{"name": "feature", "value": "UI: Авторизация"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_login_page"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "25968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_login_page"}]}