{"name": "test_fail_delete_task", "status": "passed", "description": "Проверка ошибки при удалении задачи с некорректными заголовками", "steps": [{"name": "Обновляем заголовки на некорректные", "status": "passed", "start": 1744826068492, "stop": 1744826068492}, {"name": "Пытаемся удалить задачу", "status": "passed", "start": 1744826068492, "stop": 1744826068565}, {"name": "Возвращаем заголовки и убеждаемся, что задача осталась", "status": "passed", "start": 1744826068565, "stop": 1744826068914}], "start": 1744826068492, "stop": 1744826068914, "uuid": "d1d4abee-9c81-4c0f-9635-ac17d7a97300", "historyId": "fca0feda91469001c721842c2aa8b58f", "testCaseId": "fca0feda91469001c721842c2aa8b58f", "fullName": "tests.api.test_tasks.TestTasks#test_fail_delete_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "28392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}