{"name": "test_success_delete_task", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == 204\n +  where 400 = <Response [400]>.status_code", "trace": "self = <clickup_tests.tests.api.test_tasks.TestTasks object at 0x000001E3EEBE78F0>, tasks_client = <api_clients.tasks.TasksClient object at 0x000001E3EEBE4A40>\ncreate_and_delete_task = {'archived': False, 'assignees': [], 'checklists': [], 'creator': {'color': '', 'email': 'sanches2101@gmail.com', 'id': 182699604, 'profilePicture': None, ...}, ...}\n\n    @allure.description(\"Проверка успешного удаления задачи\")\n    def test_success_delete_task(self, tasks_client, create_and_delete_task):\n        task_id = create_and_delete_task[\"id\"]\n    \n        with allure.step(\"Удаляем задачу\"):\n            response = tasks_client.delete_task(task_id=task_id)\n>       assert response.status_code == 204\nE       assert 400 == 204\nE        +  where 400 = <Response [400]>.status_code\n\ntests\\api\\test_tasks.py:102: AssertionError"}, "description": "Проверка успешного удаления задачи", "steps": [{"name": "Удаляем задачу", "status": "passed", "start": 1744826067415, "stop": 1744826067486}], "start": 1744826067415, "stop": 1744826067486, "uuid": "15dea9fd-7104-4c46-a5d1-47b5d1cb99e0", "historyId": "93a01b606b622308dccbab27f0d7f5f4", "testCaseId": "93a01b606b622308dccbab27f0d7f5f4", "fullName": "tests.api.test_tasks.TestTasks#test_success_delete_task", "labels": [{"name": "feature", "value": "API: Работа с задачами"}, {"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Grw-pc"}, {"name": "thread", "value": "28392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}