{"uuid": "11cd544d-fa4b-4aff-ba09-0bbc4968ae4d", "children": ["17165f75-0bd4-4717-97f4-1a85150153e9", "3f6ad8a2-2ce9-4824-acc6-1c1c05ebb4ec"], "befores": [{"name": "sync_browser", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nPlease use the Async API instead.\n", "trace": "  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py\", line 84, in sync_browser\n    playwright = sync_playwright().start()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_context_manager.py\", line 84, in start\n    return self.__enter__()\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_context_manager.py\", line 47, in __enter__\n    raise Error(\n"}, "steps": [{"name": "Запуск браузера Playwright", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nPlease use the Async API instead.\n", "trace": "  File \"c:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\tests\\conftest.py\", line 84, in sync_browser\n    playwright = sync_playwright().start()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_context_manager.py\", line 84, in start\n    return self.__enter__()\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Sanchez\\Documents\\GitHub\\clickup_tests\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_context_manager.py\", line 47, in __enter__\n    raise Error(\n"}, "start": 1744799760450, "stop": 1744799760450}], "start": 1744799760450, "stop": 1744799760450}], "start": 1744799760450, "stop": 1744799760464}